### PR TITLE
new-egg upstream rhel-7.5plus merged into master

### PR DESCRIPTION
**Pull request by eduardocerqueira**
merged rhel-7.5plus

### CODE REVIEW

**Comment by eduardocerqueira** [comment]
test this please

**Comment by YakovLittle** [comment]
test this please

**Comment by eduardocerqueira** [comment]
test this please

**Comment by eduardocerqueira** [comment]
test this please

**Comment by eduardocerqueira** [comment]
test this please

**Comment by eduardocerqueira** [comment]
test this please

**Comment by eduardocerqueira** [comment]
test this please

**Pull request closed without merging**
