### PR TITLE
pipeline test file

### PR DESCRIPTION
**Pull request by eduardocerqueira**
adding pipeline test file

### CODE REVIEW

**Comment by eduardocerqueira** [comment]
retest this please

**Comment by eduardocerqueira** [comment]
retest this please

**Comment by YakovLittle** [comment]
retest this please

**Comment by eduardocerqueira** [comment]
retest this please

**Comment by eduardocerqueira** [comment]
retest this please

**Comment by eduardocerqueira** [comment]
retest this please

**Comment by eduardocerqueira** [comment]
retest this please

**Comment by eduardocerqueira** [comment]
retest this please

**Comment by YakovLittle** [comment]
retest this please

**Comment by YakovLittle** [comment]
retest this please

**Pull request merged**
